import Head from "next/head";
import {
  Center,
  Container,
  HStack,
  Heading,
  Text,
  Button,
  IconButton,
} from "@chakra-ui/react";
import NavBar from "@/components/Navigation/NavBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="container.md" minH={'100vh'} centerContent>
        <NavBar />
        <Center mt={8}>
          <Heading as="h1" size="lg" textAlign="center">
            Yet another link shortener <br /> No frills, just links
          </Heading>
        </Center>
        <Text mt={4} color="gray.600" textAlign="center" maxW={"40rem"}>
          Simplify link management <br />
          Effortlessly shorten, securely share, and gain insights through
          analytics.
        </Text>
        <HStack mt={6} spacing={4}>
          <Button
            color="white"
            bgColor="#333333"
            fontSize={"small"}
            fontWeight={"400"}
            _hover={{ bgColor: "black" }}
          >
            Get Started
          </Button>
          <IconButton
            as="a"
            href="/"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="GitHub"
            icon={<GitHubIcon />}
          />
        </HStack>
      </Container>
    </>
  );
}

const GitHubIcon = () => {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      className="feather feather-github"
    >
      <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path>
    </svg>
  );
};
