import Head from "next/head";
import { Container } from "@chakra-ui/react";
import { useAuth } from "@/contexts/authentication";
import Landing from "@/layouts/Landing";
import NavBar from "@/components/Navigation/NavBar";
import AuthWrapper from "@/components/AuthWrapper/AuthWrapper";

export default function Home() {
  const { isAuthenticated } = useAuth();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="container.md" minH={"100vh"} centerContent>
        {!isAuthenticated ? (
          <>
            {isAuthenticated !== null ? (
              <>
                <NavBar />
                <Landing />
              </>
            ) : null}
          </>
        ) : (
          <AuthWrapper>
            <NavBar />
            <Container>Yay Home!!</Container>
          </AuthWrapper>
        )}
      </Container>
    </>
  );
}
